CREATE TABLE "Order"
(
    orderid                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userid                 INTEGER,
    unregisteredcustomerid INTEGER,
    deliverytypeid         SMALLINT,
    posttime               TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    completetime           TIMESTAMP WITHOUT TIME ZONE,
    status                 CHAR(1)                                  NOT NULL,
    total                  numeric(12, 2),
    CONSTRAINT Order_pkey PRIMARY KEY (orderid)
);

CREATE TABLE "User"
(
    userid       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phonenumber  VARCHAR(10)                              NOT NULL,
    email        VARCHAR(80),
    firstname    VARCHAR(30)                              NOT NULL,
    lastname     VARCHAR(30),
    hashpassword VARCHAR(512)                             NOT NULL,
    access       CHAR(1)                                  NOT NULL,
    region       VARCHAR(30),
    district     VARCHAR(30),
    city         VARCHAR(30),
    street       VARCHAR(30),
    building     SMALLINT,
    apartment    SMALLINT,
    postalcode   INTEGER,
    CONSTRAINT User_pkey PRIMARY KEY (userid)
);

CREATE TABLE orderproducts
(
    orderproductsid INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    orderid         INTEGER                                  NOT NULL,
    productid       INTEGER                                  NOT NULL,
    quantity        INTEGER                                  NOT NULL,
    sum             numeric(12, 2),
    CONSTRAINT orderproducts_pkey PRIMARY KEY (orderproductsid)
);

CREATE TABLE deliverytype
(
    deliverytypeid SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(50)                               NOT NULL,
    CONSTRAINT deliverytype_pkey PRIMARY KEY (deliverytypeid)
);

CREATE TABLE producttype
(
    producttypeid SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(30),
    CONSTRAINT producttype_pkey PRIMARY KEY (producttypeid)
);

CREATE TABLE unregisteredcustomer
(
    unregisteredcustomerid INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phonenumber            VARCHAR(10)                              NOT NULL,
    firstname              VARCHAR(30)                              NOT NULL,
    lastname               VARCHAR(30),
    region                 VARCHAR(30)                              NOT NULL,
    district               VARCHAR(30),
    city                   VARCHAR(30)                              NOT NULL,
    street                 VARCHAR(30)                              NOT NULL,
    building               SMALLINT                                 NOT NULL,
    apartment              SMALLINT,
    postalcode             INTEGER,
    CONSTRAINT unregisteredcustomer_pkey PRIMARY KEY (unregisteredcustomerid)
);

ALTER TABLE "User"
    ADD CONSTRAINT User_email_key UNIQUE (email);

ALTER TABLE "User"
    ADD CONSTRAINT User_phonenumber_key UNIQUE (phonenumber);

ALTER TABLE "User"
    ADD CONSTRAINT uk_9t4er00mstv8by4kyik0uong0 UNIQUE (email, firstname, lastname, phonenumber);

ALTER TABLE deliverytype
    ADD CONSTRAINT uk_kw70gvy0iwcix964oxipib4ct UNIQUE (name);

ALTER TABLE producttype
    ADD CONSTRAINT uk_k770d2e0gmnvmrd61d8j14gv UNIQUE (name);

ALTER TABLE unregisteredcustomer
    ADD CONSTRAINT unregisteredcustomer_phonenumber_key UNIQUE (phonenumber);

CREATE TABLE product
(
    productid   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(128)                             NOT NULL,
    description TEXT,
    price       numeric(10, 2)                           NOT NULL,
    stock       INTEGER                                  NOT NULL,
    CONSTRAINT product_pkey PRIMARY KEY (productid)
);

CREATE TABLE product_producttype
(
    product_productid          INTEGER NOT NULL,
    producttypes_producttypeid INTEGER NOT NULL
);

CREATE TABLE typeunit
(
    productid     INTEGER  NOT NULL,
    producttypeid SMALLINT NOT NULL,
    CONSTRAINT typeunit_pkey PRIMARY KEY (productid, producttypeid)
);

ALTER TABLE "Order"
    ADD CONSTRAINT Order_deliverytypeid_fkey FOREIGN KEY (deliverytypeid) REFERENCES deliverytype (deliverytypeid) ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "Order"
    ADD CONSTRAINT Order_unregisteredcustomerid_fkey FOREIGN KEY (unregisteredcustomerid) REFERENCES unregisteredcustomer (unregisteredcustomerid) ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "Order"
    ADD CONSTRAINT Order_userid_fkey FOREIGN KEY (userid) REFERENCES "User" (userid) ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE product_producttype
    ADD CONSTRAINT fkajl671ltewg4fsadmyjad9pn7 FOREIGN KEY (product_productid) REFERENCES product (productid) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE product_producttype
    ADD CONSTRAINT fkj25io6fkj85xx4h0433dc3m4t FOREIGN KEY (producttypes_producttypeid) REFERENCES producttype (producttypeid) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE orderproducts
    ADD CONSTRAINT orderproducts_orderid_fkey FOREIGN KEY (orderid) REFERENCES "Order" (orderid) ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE orderproducts
    ADD CONSTRAINT orderproducts_productid_fkey FOREIGN KEY (productid) REFERENCES product (productid) ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE typeunit
    ADD CONSTRAINT typeunit_productid_fkey FOREIGN KEY (productid) REFERENCES product (productid) ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE typeunit
    ADD CONSTRAINT typeunit_producttypeid_fkey FOREIGN KEY (producttypeid) REFERENCES producttype (producttypeid) ON UPDATE NO ACTION ON DELETE CASCADE;